# Generated by Codex for Student 5 verification support on 2026-04-28.

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['-created_at', '-id']},
        ),
    ]
