# Generated by Django 5.0.6 on 2026-04-28 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0002_alter_auditlog_id_alter_department_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dependency',
            options={},
        ),
    ]
